In [1]:
import numpy as np

def covariance_matrix(vectors):
    """
    Calculate the covariance matrix from a list of vectors.

    Parameters:
    vectors (list of lists): A list of vectors, where each vector is a feature.

    Returns:
    cov_matrix (numpy array): The covariance matrix.
    """
    # Convert the list of vectors to a numpy array
    vectors_array = np.array(vectors)

    # Calculate the mean of each feature (vector)
    means = np.mean(vectors_array, axis=1)

    # Subtract the mean from each feature to center the data
    centered_vectors = vectors_array - means[:, np.newaxis]

    # Calculate the covariance matrix
    cov_matrix = np.dot(centered_vectors, centered_vectors.T) / (centered_vectors.shape[1] - 1)

    return cov_matrix

# Example usage
vectors = [[1, 2, 3], [4, 5, 6]]
cov_matrix = covariance_matrix(vectors)
print(cov_matrix)

[[1. 1.]
 [1. 1.]]


In [3]:
import numpy as np

def calculate_covariance_matrix(vectors):
    """
    Calculate the covariance matrix from a list of vectors.

    Parameters:
    vectors (list of lists): A list of vectors, where each vector is a feature.

    Returns:
    cov_matrix (numpy array): The covariance matrix.
    """
    # Convert the list of vectors to a numpy array
    vectors_array = np.array(vectors)

    # Calculate the mean of each feature (vector)
    means = np.mean(vectors_array, axis=1)

    # Subtract the mean from each feature to center the data
    centered_vectors = vectors_array - means[:, np.newaxis]

    # Calculate the covariance matrix
    cov_matrix = np.dot(centered_vectors, centered_vectors.T) / (centered_vectors.shape[1] - 1)

    return cov_matrix

# Test Case 1
print(calculate_covariance_matrix([[1, 2, 3], [4, 5, 6]]))
# Output: [[1.0, 1.0], [1.0, 1.0]]

# Test Case 2
print(calculate_covariance_matrix([[1, 5, 6], [2, 3, 4], [7, 8, 9]]))
# Output: [[7.0, 2.5, 2.5], [2.5, 1.0, 1.0], [2.5, 1.0, 1.0]]

[[1. 1.]
 [1. 1.]]
[[7.  2.5 2.5]
 [2.5 1.  1. ]
 [2.5 1.  1. ]]
